1-ая часть ДЗ №2
htmlacademy-htmlcss/1690431-technomart-31 pull request #2
Opened 2021-05-21 21:02 UTC by marchell93

2021-05-22 10:57 UTC, ValeryKrukovich requested changes

2021-05-22 10:57 UTC, ValeryKrukovich commented on index.html
> +      <a href="#">
Тут атрибут href лишний, главная ссылается сама на себя, это не совсем корректно.

2021-05-22 10:57 UTC, ValeryKrukovich commented on index.html
> +        <img src="https://via.placeholder.com/220x47" width="220" height="47" alt="Логотип">
содержимое тега alt я бы предложил расскрыть более подробно. Логотип чего, чей? 
Предлагаю - Логототим интернет-магазина «Техномарт»

2021-05-22 10:57 UTC, ValeryKrukovich commented on index.html
> +      </p>
Тут можно сразу добавить семантический тег, который сделает текст курсивом и выделит его добавив смысловое значение.

2021-05-22 10:57 UTC, ValeryKrukovich commented on index.html
> +        </figure>
Кнопки вперед и назад явно не должны входить в тег figure.
Загляни в демку барбершопа, посмотри как верстали эту секцию лекторы, это поможет понять.
По техническому заданию верстка всех слайдов обязательна, посмотри в макете должны быть еще слайды.
Если ты просто пока пропустил это, то ок, потом будет время еще доверстать это.

2021-05-22 10:57 UTC, ValeryKrukovich commented on index.html
> +          </li>
Не соответсвет техническому заданию, тут карточки должны быть ссылкой.
Смотри пункт 3.9 т.з

2021-05-22 10:57 UTC, ValeryKrukovich commented on index.html
> +          поднимая его на ваш этаж!</p>
Тут тоже по т.з. несколько слайдов.
Но если ты осознанно оставил на потом, то ок.

2021-05-22 10:57 UTC, ValeryKrukovich commented on index.html
> +        <h2>Верхняя часть футера</h2>
Мне кажется не совсем корректный заголовок. Он не описывает контент который находиться в секции. Это больше похоже на комментарий к коду.

2021-05-22 10:57 UTC, ValeryKrukovich commented on index.html
> +          <img src="https://via.placeholder.com/220x47" width="220" height="47" alt="Логотип">
Ссылка страницы самой на себя не корректна. Тут как и в шапке можно оставить тег а без атрибута href, а на внутренних страницах добавить этот атрибут

2021-05-22 10:57 UTC, ValeryKrukovich commented on index.html
> +
Плюс не сверстаны попапы, я могу пока не учитывать это если ты осознанно оставляешь это на потом.

2021-05-22 20:12 UTC, marchell93 commented on index.html
> +      </p>
Done

2021-05-22 21:14 UTC, marchell93 commented on index.html
> +        </figure>
Done, в макете не увидел, что есть скрытые слои, буду сразу верстать сразу все

2021-05-22 21:17 UTC, marchell93 commented on index.html
> +          </li>
Done

2021-05-22 21:24 UTC, marchell93 commented on index.html
> +          поднимая его на ваш этаж!</p>
Done

2021-05-22 21:26 UTC, marchell93 commented on index.html
> +          <img src="https://via.placeholder.com/220x47" width="220" height="47" alt="Логотип">
Done

2021-05-22 21:37 UTC, marchell93 commented on index.html
> +        <h2>Верхняя часть футера</h2>
Done

2021-05-22 22:03 UTC, marchell93 commented on index.html
> +
Done. Не правильно интерпретировал первый пункт ДЗ. Все сделал.

2021-05-23 11:37 UTC, ValeryKrukovich approved these changes

2021-05-23 11:37 UTC, merged