2 задание ДЗ №2
htmlacademy-htmlcss/1690431-technomart-31 pull request #3
Opened 2021-05-24 12:45 UTC by marchell93

2021-05-24 14:47 UTC, ValeryKrukovich requested changes

2021-05-24 14:47 UTC, ValeryKrukovich commented on catalog.html
> +      </form>
А почему ты решил что тут форма? Пересмотри этот блок.

2021-05-24 14:47 UTC, ValeryKrukovich commented on catalog.html
> +        <fieldset>
Добавить отступ,  теряется вложенность.

2021-05-24 14:47 UTC, ValeryKrukovich commented on catalog.html
> +        </ul>
Не хватате еще сортировки в виде стрелочек.
Сортировку для интернет магазинов чаще делают ссылкой а не кнопкой, это связанно с реализацией функционала с помощью  php. Были вопросы на защите у моих студентов с реализацие кнопками. Лучше переделать. С опытом ты сам поймешь, почему так

2021-05-24 14:59 UTC, marchell93 commented on catalog.html
> +        <fieldset>
Done

2021-05-24 19:38 UTC, marchell93 commented on catalog.html
> +        </ul>
Done

2021-05-24 19:57 UTC, marchell93 commented on catalog.html
> +      </form>
Done

2021-05-25 21:17 UTC, ValeryKrukovich approved these changes

2021-05-25 21:17 UTC, merged