Стилизация главной страницы
htmlacademy-htmlcss/1690431-technomart-31 pull request #5
Opened 2021-06-01 12:22 UTC by marchell93

2021-06-02 06:06 UTC, ValeryKrukovich requested changes

2021-06-02 06:06 UTC, ValeryKrukovich commented on css/style.css
> +.feedback a,
Вот тут мне кажется лишние селекторы с тегом a.
font-size: 16px;
line-height: 18px; будут наследоваться, а цвет ты переопределяешь следующим блоком правил

2021-06-02 06:06 UTC, ValeryKrukovich commented on css/style.css
> +.develop:hover a {
Псевдоклас :hover, :active нужно вешать на тег a ведь он интерактивный элемент.
И по коду выше и  ниже, где есть такое, тоже нужно поправить.

2021-06-02 06:06 UTC, ValeryKrukovich commented on css/style.css
> +  font-family: "PT Sans";
Нужна задать альтернативный шрифт и семейство шрифтов, на случай если это шрифт не загрузиться.

2021-06-02 07:01 UTC, ValeryKrukovich requested changes

2021-06-02 07:01 UTC, ValeryKrukovich commented on css/style.css
> +  background-color: var(--basic-white);
Есть требование:
3.1. Контентная область центрируется и не может быть уже макетной ширины. Фоны, которые упираются в края макета, должны тянуться на всю страницу.

у тебя не учтено

2021-06-02 07:36 UTC, marchell93 commented on css/style.css
> +.feedback a,
done

2021-06-02 08:03 UTC, marchell93 commented on css/style.css
> +.develop:hover a {
done

2021-06-02 08:11 UTC, marchell93 commented on css/style.css
> +  font-family: "PT Sans";
done

2021-06-03 07:09 UTC, ValeryKrukovich approved these changes

2021-06-03 07:10 UTC, merged